---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: unifi-dns
  namespace: network
spec:
  endpoints:
    - dnsName: "unifi.${SECRET_DOMAIN}"
      recordType: A
      targets: ["192.168.1.21"]  # Replace this with your actual Unifi controller IP 