---
apiVersion: v1
kind: Service
metadata:
  name: unifi-external
  namespace: network
spec:
  type: ExternalName
  externalName: 192.168.1.1
  ports:
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-external
  namespace: network
spec:
  ingressClassName: internal
  rules:
    - host: unifi.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi-external
                port:
                  number: 443 