---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age15e9y0cxs5vw2uvxtts2yz2dvnmefpw5054ahlkwmnulfcwy5zyqqrgc8cc"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age15e9y0cxs5vw2uvxtts2yz2dvnmefpw5054ahlkwmnulfcwy5zyqqrgc8cc"
