---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1agf0jp7qyqngf9kn5cn5cd9z24dgsu38rtu5l0hmjsfd6qn50pvsh38rsa"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1agf0jp7qyqngf9kn5cn5cd9z24dgsu38rtu5l0hmjsfd6qn50pvsh38rsa"
stores:
  yaml:
    indent: 2
