# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:2LwYymYSwaQ6dTgus7S9Ph7RdKa/YDBHTHgHUBNrfc4=,iv:5I38qeuUw7FGERThzNxOUuV4c+r9wVSV+G3ZIlU7VTk=,tag:t7NZGZ/1RiIT1qPVsmnZ4Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1agf0jp7qyqngf9kn5cn5cd9z24dgsu38rtu5l0hmjsfd6qn50pvsh38rsa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aEQ2enRxcEV6Uk1zcHVt
        bXhSUHVjb2IvVUJtbDducGN2Zi83eVBIbjNjCk14YjhXWW9DaitVNVRZUVJLVVlw
        KzFzckdhc1BRSThFK001anNYL3hmN2sKLS0tIE9DcVZNSlZyYWMyckM4aU85YVRU
        V1c4WUxRTHBXZFVFV3ZEYUc2bEVPR2cKQeO3LW7PyLJiNqvbUYQt+fVBqb3ZZ1WP
        8IpwPJI+AY8NO/LKM6z41+trtDoyvekOFlkgf5bvN0/gRqVqqX86xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-19T16:02:18Z"
  mac: ENC[AES256_GCM,data:6JmH9ZyMmaNz1yo80Gcqzvdk15gdwF+pPIy4YzoMx2mUasMLEZWvFQy6gLwx+TjAUA1/VDZvu/VzZzMxHBVi/tWhMIcAypq4V361CUGSEnP5AYooH+4iM81RVaOQD5gz4RpyByOLTTXACp7JfL39y44A37oyGjXXlLPqTUBjesg=,iv:S2tkPt8+0kBIEmg2rj92X68eYHBdR5gb0173Al9DRaM=,tag:zSPCK9e1Srf624pmsT6Bfw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
