# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Q01GzR/IOrdi66wOVtO21oigSgDDcsa9G1LzTFZyUqk=,iv:Wr8qrcPlrBK8lHpRo3Qf+PC1VSxvEueIjW5QrWC5XL8=,tag:ILOdKWqLufLsn1X1LP0sXg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMnFzc3ljRCtPRjNmWnZN
        QXVZc2ZZMmhvR09yM0UwNmRUZWJCZGlUYjFvCmh6WVhYN05GZVZOMnd4bnlLcHdO
        N0RyQXhidjRHSFM1dU9rQ0RLK2RlRkUKLS0tIFpxQ1pkc0V3Nkk5VEFUcUdHOWVY
        ZCsyaEpUdGNTK2FuNFZ6dVM1VXpuTUkKcrb9gnwBhN1HS5bLkA/gdbaj+0gpQ+LM
        TMQrVTqBItat47b0UjrivxAcqqK3CBC1X0JgEOnSwIXftGy4MQ+++g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T19:56:28Z"
  mac: ENC[AES256_GCM,data:9ikehbRVbpT52lvY/RIrzAtGHvWHiHR72nLWNeZ7RtIe8iGBRWDZh4IFI9VNCTVCkfhqVQ80xD92nxX2xXuszfmpxdyOrxwdeVvLL4tguwAaFSb1x3IdGUk7yk749jk1yLZre/ygMNnhe52LDQZsMQO7xd97KHNCnQB7HhvWuCU=,iv:rEbSZO6i52UgIqe885h7IzHjSR5pejsiFY6717+L+Tc=,tag:49Agpl+FhucQY4rS8izgJg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
