# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:xdyNO0XjdF7ZPlwJPYLns8yQ5zNl/s0L1OLil/6ktxU=,iv:KncERrI1nWhG5R6Z954r6GdYvS+4bB0YJEQl/1IzQNE=,tag:byA9ddEjcNiIc8y7nKYeNg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcmpyaFlBTlp4cjJua0o3
        akphOHozeHZGR3hvbTVVOUZWLzRmaDRhclF3Ci9CeURKQWxHZFdOQWtBN3Q2L3NY
        TUd3MEJQT1NFQXNzY1BNcUt4SGNYbG8KLS0tIDRHUlZpR2JqRGtEL3FjV09GWUlZ
        Ry9LcGVBQUl0RlVFTy9HS3orZzRYU3MKGhsKO+2weNXtI9rXhyR+2X/B7CEj64Et
        Um8GS+5WM3UzDbcuIC4SGl5+x10hxbN4s+wC6/E3A9IrrFNtFC7IUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T19:38:27Z"
  mac: ENC[AES256_GCM,data:KimsB2MqLphTUF7gS62d/BakxI2vFl4NKGHRW6pymOouHUVn/mIAdU7OuBpBnOrez9XrQom8uf95U3Dn9iiKHDobDAawVN94iR6vLOqQuSB/5fxk7Hk1APZMnZ+EobN9rTdsWx/L2o3XttdtWwU3zDzpQJFvG8JXcPuHOjtqY+8=,iv:FTI/DlDZyu+gBiRagGEu5OWi+3oFq4oIfxTSkdTL3kU=,tag:unhbb7ptGnYI96sSBOVMSA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
