# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-vpn-secret
stringData:
  SECRET_TZ: ENC[AES256_GCM,data:GsmB6ZUGRgXuGz8vXA==,iv:+IfP3M6Q1FOccEWEMGBKwh9x0dRRib1PqjJJqJuZMBQ=,tag:xBvHQZSIDyT1rBlxaTrzCQ==,type:str]
  SECRET_VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:R7DzAA6k2w==,iv:y0COWPuhr2LucZnVaIdrjrja3JuVx/F/aEgH2PA2mDk=,tag:vDdX2ZrVR+CxXbOf6ZaS8A==,type:str]
  SECRET_WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:5Fc2oqFqKqTfyvM6qEbxudc4xlsZrUIs6uaO4hkpS6Ou0OzbQKf7G1BhIzo=,iv:LFaIDbgPiLlhcN3Nqku5nut77vpZ81ORMTThF8AQRNw=,tag:d2gpejziIyFRRttio9Ghrw==,type:str]
  SECRET_WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:vKry30Eqng2FTGXwlmu0FQ==,iv:O/XxOPvTC1o875xhkXO6VRjrkj+dMHT7r+YpwAmOlaM=,tag:TjVF6xnIeIBCCF1J+FGOtQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTelhVTCtyVDdwT21SSnh6
        RklHOFpEMFlUVWJYcXZIZ0wzS2c4QmViUlY0CkRtUTFmTDlFU3B3VTVSNU1nQThK
        dEVEVjU4bllGc1JaNitKb3YvdUg5bzgKLS0tIEJUa1dYUkxoL3c2aUl5SldQdll4
        NDYzU01aR1grRFEvUXcvbUx3VUw5aTgKUjt5Ko9cEMcQZ9HnRpS7//CcBj9aiAuL
        uGscBQWUG828XNheyyemPyDWaV0+5sRMpXPVdWqs1Qg4ubm/eZkwbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T17:31:43Z"
  mac: ENC[AES256_GCM,data:SXpJSG4+44zmYmkaicfU9/JlQyzTXIk0SQB3XodobSX9XS0TYBYH6fXXGhNSMmOtGxnbwuA765UAuZ6tQ3KLl1UuFtXb6/GFPEN6VRn5NI6PcybJflFW9IqL9XGN9vgNABDOKvFZPhXux/KqHN8Z7hL2eQBolXCWhYY6zq/IHQM=,iv:aTu7UzGEfZGi2Sh1eIfeihvRgks5S6Qa3udjlpqqVoI=,tag:P+j5RxEvrBaSvgYiZe9eeQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
