---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: "${APP}-volsync-secret"
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        KOPIA_REPOSITORY: filesystem:///repository
        KOPIA_FS_PATH: /repository
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: /volsync/KOPIA_PASSWORD
