---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${VOLSYNC_CLAIM}-repo"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-volsync
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
