---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.10.3
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 1000m
                memory: 3000Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 10000Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Range $http_range;
            proxy_set_header If-Range $http_if_range;
          nginx.ingress.kubernetes.io/proxy-body-size: "50m"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: jellyfin-config
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config/transcodes
      media:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_DOMAIN}
        path: /mnt/user/Media
    env:
      TZ: "Europe/London"
      DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
      JELLYFIN_FFmpeg__probesize: "50000000"
      JELLYFIN_FFmpeg__analyzeduration: "500000000"
      JELLYFIN_CACHE_DIR: "/config/cache"
      JELLYFIN_CONFIG_DIR: "/config"
      JELLYFIN_DATA_DIR: "/config/data"
      JELLYFIN_LOG_DIR: "/config/log"
      JELLYFIN_WEB_DIR: "/usr/share/jellyfin/web"

    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 3000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 10000Mi 
