# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:nfxIZVCCxkSK+nicaFsL51472Jxw7SPRjXE7NhYYkNP2pPeGjNPINQ==,iv:Awm4nBL+KLw09ojj6wOdb3PhZ0lAJ7QanaEkagRGHhA=,tag:oW6dCwvhO0FoC1K37JF4ng==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1agf0jp7qyqngf9kn5cn5cd9z24dgsu38rtu5l0hmjsfd6qn50pvsh38rsa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdEY3eG1JREJpSERNaFFV
        M25QOXkwTG80aURYZ1BZZHFpNHM0VkpRbFRjCmx5Ky80Z0FnQzVoSW1NNmJsUDh3
        cUdUaG56Sm81a3dCS2tIcW1ya21oVXcKLS0tIFVMdVNpdjFpTGRPYXZoZ0xUaW82
        MlMzUFRqUmdqOVVLSFVVK0QyVWZiWXMK/0bKYYMcabl0B1BSaITEuxb2rrlPtWvH
        5FfDr1lCtfwSCTjIq5qVuVAyIit1ycwRVomPhgYHAQv/W0S+AC1dLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-19T16:02:18Z"
  mac: ENC[AES256_GCM,data:j1+BCO9OOVblrRfr5ozVD/FkUv9uWr9vG42o+VNUcmszLuR5gAmxaafw+ibH0KuJIgFaZ/+ngOlN+cNhvdvOVtigwzdLQjVkZxkWeNwMGQ0GTKQlfix0loAA8MKvVXdywFehuYhLJvv6GnK6Bc3BQZVwtSNetiIHW1KW/gTKwDo=,iv:rfoNeyo4IfNpoTn0OdxWGpoJWF/wycPCCYG4bLWpcFM=,tag:fVBLYZmkX/tYAoIboUCWIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
