# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:bg2Z8KDscw9tQ2rWeq229M/auYfBi5A9A8MzNAovRNCQGV2pOj6bUg==,iv:odQlKvkri2ONGUJKW9mCvB+G5qNAkNY/arvNAtFbw+U=,tag:ypujLppfH+Zvt3ACQ08Y2Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R3lXL2o3eXZZeUszYkNy
        RHVubFRBeDhCOHFLaWdrU0tseHN2UGtmNzBFClVnNGRyWGFoSmFyWmJaVWgwOVVT
        SHVFVWRteHdHYXJvYTdsZjRTeS9Ta0EKLS0tIEJ1aXFNUzhQWEFKRFQ5VElQb2lk
        eHlQeE5OWU5RVE5rczBUdmJQZ21rUkEKy7jT0koB2K7VRw7o5x8LssmnmQEa9D1f
        j1S8Q/fMxLK4CIGdAha1IodIRZ0ZVfTTzMdNeJAPysfiuSBtGXDuvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T19:38:27Z"
  mac: ENC[AES256_GCM,data:m0Q1YOO2IhNUvbXLk1l7b3947LKIXZvpaEBOav1447Sx/WOI16JCjsuiV1MKgGGv4Tq7/5iyb8+Sjs0/VqX+3t3sDnlWI5TYSt4gvqYA+RwsR1Pz3EgeYGIe0kvuPqkt9/ItoKPbRTj3AiydDnKmMQ8gtTkyS4XrRoOX5K3/19M=,iv:gJEgEr/aKZaKqiP4YO7jb4Q4tE1kaoIqePOUvFF2JTY=,tag:iZh5H91lM8fyj9o/365eBw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
