# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:341pvs+X+gSceCmo/2LErUWb0tLRkhKPmGmqsw0Sj4AwI554mL3UrA==,iv:PyFJ0SZgGql/+bHlHkqj+r28MDsuQq+4ont2dUkzE4s=,tag:SSOw5wd8AhKMtcKIQjN+4Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S1dRekdwaHQ2enUxenpn
        b3FUMmFFK1Y2QUFWYmhHdDV5ZGNWcVdPbG40CkZDUFQxYWFOejQ2OXJ3aDlJd1o2
        SmxpNzd2Q3ZiVlVMSVFiNStLa1BjSVkKLS0tIGNURjhJTy9hMDlhOEtTN3BuMFpt
        bUNIclI1SnNNTE9wUVNTQ3BhMGxRY2sKNdQGh+0uzzyMAbNhfGYT61JWZq0fqb3v
        0ZgZtMq3EZDUX6ZbaZsQHhdG2feTQ1KFT2HXf5D70Xf0fLEQ50DqMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T19:56:28Z"
  mac: ENC[AES256_GCM,data:HyQ51BhXgkMCMVFqepawEYfxD2kHEI32VKlGAH6gV+VQ2uP8My4u3SlD04L8akMvlcue0P1MmS6dzhEFrmt+gL4XhK9rlu1Pn2bV1W5E0ak69mvhIoaSg+8m/d0pMyWn9+yDn7GsFln1HVV3Zh2EshNbh9MuGg2uiIdgWYItJ0o=,iv:9XooyMaYnmgKNVjSgGmTh9BtZMopc45yvgWR8hJ5CaI=,tag:PfquXBDGGmDa243eP97j/g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
