---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gluetun
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/qdm12/gluetun
  type: oci 