---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi
