apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:AKFB7SGGKkn8oNSFZ19Il3SjLhnncHhqxLteIbbZJX1YdYqHFRstqrE5InW1WDZSBBtscxGozeaWwraUzYDGkAmcvM2+xxf+WBDVtQe/gaEM,iv:gkv53Ku0+nCHnYHu9rShqCQTANXZDFkQc1sWqB0fYiE=,tag:6Zdc5m2hQcZDUgx4zIGIjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15e9y0cxs5vw2uvxtts2yz2dvnmefpw5054ahlkwmnulfcwy5zyqqrgc8cc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a0FHd2Z0MXJZOTV2OURj
            eC9GS0lYT3VpYnZwRDVESlM2ZEZnbVZyU0VzCmdrcFFrczlEdys1ZUdmQ1VHaHFB
            NURyWlBrcGoybmRXVkxXcUJlejYwbkkKLS0tIGs3TDQvdDltRWNPOVN3V2xXaTBM
            WkI0YkJJMERTQTNDOWhPTUxXR08xNzQK/q9rWdAazE+0vNyQMb88lBhJbqMM6zMc
            GOAlvznTLiE5NrElfo4jJnLuSBE8ddkXqURnjeudno9M05FyJb0JQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T15:02:26Z"
    mac: ENC[AES256_GCM,data:aEJv2/FBpHeQRKvbalYZnqdY5/g/1jm95CJZFtdt/Q7JAU8B/VJHM27uw8Z83P/bfpKTFfWTHLH/J+frkAIIlSvtU7R8BBTFAS7OjEeqxr6S37sm1YUfJrMi9FMRbCBGAbNlsFPOMJcVGhXvInPBi8jcypj7tlFSMoxmfsJT7Rk=,iv:3wQiBil3drnyRuaPIzb2Hnsu/A4f6WWf6i8IHPxFOkA=,tag:ygVPUbSIHc+FXNedCgzKfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
