apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:NaugQnZtMFkPt23s8xis3ZqE1W0+Q3IwCdzokTs07snbu6qRKA4jsc1Uq8ybc5QdsB3VaKROOE4wDqBi2fVmxoq47MJFHz6tYacgHkpNlbWw,iv:CpchlCxDyBIvCvSFppgo74vPSCLrX0OOEBI2Dcnzda0=,tag:eSq+aUH1yWolUQvoq6hCiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvqhp4ya7s0hxpxvttjsltg5m2dztsywrf70jx9ee7vwg9t465aqqvdht0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTEFXNzRWY0NUc1pIMkVZ
            UFpTYWdubUZuS2ZOMlk3dUk2WDlidFFKMnkwCkJUYTd0c0kwMHEwSDJBNk45T2dU
            cUwwaW9QWHdxRXdZSWFBeFhLZmhxVUkKLS0tIFlSNEtucnhUcVpRM2h1TlhiUnNX
            bS9jY1ZsNkxkR2VScFcrajRZUGJjSjQK0LuYRBu2I2+8DXLyz6EdggDs1w5Vh7MB
            RKtqOO7XT2sTLFHR3yG2c7hz/kZbPLZf8+NapeiPzPU1E8uZLvRA8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T13:23:03Z"
    mac: ENC[AES256_GCM,data:cwI84JVH4uUj/pXKQgXD2D7SipZJ2/AJzWHtWVcH8NiNgcMn9a5XD80lPRwW/zMH0/D4DAM50x2DhFo6czkZPM1mkLn05oX0QPGGW/dOAJi/vCrEJxMuYHbrDJIR73AtpCRpCP/NqppYLbjxNzWzzqATxq54Oh+1s4pVPKWEh7c=,iv:2HXbSBRNNNd/3Q4GrWX3WTP8QSKQxh+efW7rYxb6noU=,tag:sIcldk0kaj2zK7BgB+CHsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
