apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:TxU2rR1Q+Xqd3Zk/Sqx3WwdgwDNacAdbxUgzbE2kCfU=,iv:Upja2L0ORM7wbkGxTnR1ShfQcTJ9AZrxlusfUN/aWkA=,tag:KhiK2BgFfQbNIh0DBwOouA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvqhp4ya7s0hxpxvttjsltg5m2dztsywrf70jx9ee7vwg9t465aqqvdht0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eThuT3VkcmZyeUhjWHJN
            VjZNZmhYbzQ2eHdTd1BLT3VOL1p3WVVVUVhjCmlsQ1VSS3o3VVpmYXlIS0ZYLzdK
            NlVTUmtJV0ZTZHhVZDd2RW80MEoyRjgKLS0tIE80bWRPQlRtSnd3aFJCZXFoTzln
            SFlTMVZ6NTNoL3JyQzFJelV5OXdKMzgKpV0+FJ0Y/xtnLrhToMnu1H5oYvq4SKAp
            cSc2WXaqaxsViKoj7qXJvvWo0VeM3n4OEHcBkS6sVsaXd95O3Ti81g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T13:23:03Z"
    mac: ENC[AES256_GCM,data:ytDEPiZFyPrYQ9qiLAfXTJSaixHaLYxwbPVviX4aYWedAVGJceK/FH56btoHVooMG0eL+PrRwsoct97hpI/PmuuKsheuH6/9zPTCRkjEH2gJ/JUvQ3nAsZIGHDtpQirU7v2ZP7aXQX2m8q3BlQGb/HrDrKHZkCpxySA1N+Hh3PE=,iv:rAzErM4NeAevebW9YYwU3uoAbz5TEiEBybfshcGDqRk=,tag:Rl/c7kAQJH2yPG2qPjVAGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
