apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:z7ruWC0iWRk0nT/6ovLfAzZd3ReBewN6jfzQmTe7tWM=,iv:D4CTLCA6yUZMO51/nHQbDNnmyZKQ10nBD239BUV9Z70=,tag:Y3JUP7vLW+r9LWNIQ4btMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15e9y0cxs5vw2uvxtts2yz2dvnmefpw5054ahlkwmnulfcwy5zyqqrgc8cc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRXZ5aFU2akY4b3hsWXhm
            dnhuRXJ0d3FJTWxpV1lVNDIwT0s0UGNWdTM4CjVBZmhEWUVhTVJKdjF2Qk9NS3Ro
            OFd1bXJRTWVhMkR5VjRCQWlMdmwzRjAKLS0tIFZ6VE1rRVZPVnU2Z1B6OFRwTGJw
            UWl6K1d5Nk1rS3RDdG1MUVhVdmRNSjgKMuz7o3emMMe5lKPJqiNIy8kw5vZ8+XCG
            DnGdK96ULZzmJ+DteLvASXINsR0MdioOXN5PkXcI3JdPUGKogLZDSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T15:02:26Z"
    mac: ENC[AES256_GCM,data:kugQ2AXzMCobpaV6qMBN/G2e1BpQbqkBPlgPH7i12K/UQsC+LNSEOAwgVftXCTmZMzbJJx07KE34gDp1AoAQw0Kotv+oC6JCJ0mRbQ4WWLQ+cF0refWQpQ/RsEsKDmGeBUeJBjnKd524jVolBmq4hRUOmuD43jrfTcrSmL3ip9c=,iv:/jyKGs8G8xjsihl0NHCYfivaSDnpHpcgGcfGrhUk23E=,tag:bj/2nVq5jIU1ss8qnRrvVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
