---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    ---
  docker.yaml: |
    ---
  kubernetes.yaml: |
    ---
    mode: cluster

  services.yaml: |
    ---
    - Network:
      - Unifi:
          icon: si-ubiquiti
          href: ${HOMEPAGE_VAR_UNIFI_HOST}
          description: Unifi Controller
          widget:
            type: unifi
            url: ${HOMEPAGE_VAR_UNIFI_HOST}
            username: ${HOMEPAGE_VAR_UNIFI_USERNAME}
            password: ${HOMEPAGE_VAR_UNIFI_PASSWORD}

  settings.yaml: |
    ---
    title: Home Dashboard
    theme: dark
    color: slate
    headerStyle: boxedWidgets
    target: _blank
    layout:
      Arr:
        style: row
        columns: 3
        icon: mdi-pirate
      Downloaders:
        style: row
        columns: 3
        icon: mdi-download-circle
      Home:
        style: row
        columns: 3
        icon: mdi-home
      Media:
        style: row
        columns: 3
        icon: mdi-play-box
      Network:
        style: row
        columns: 3
        icon: mdi-lan-connect
    quicklaunch:
      searchDescription: true
      hideInternetSearch: true
      hideVisitURL: true

  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true