# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rxsdMRFYG2KCP6q0vs2H7A/XC26TsH9vTLudDy0NGe6Ny2k5jyoBhA==,iv:EbbKcO7rqsmZcUBV87ggrNkMSK/YbTEsqke7vthlf+o=,tag:lmQINNWf840yZWYcQeC3Rg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc3FiTUEvRmc5czBWelR1
        SzQxSE1mOUo4bWovY1NIUnMzOENCVC9xa1FvCklLejNVNGVjZ3BrRG9pRmNiZTNk
        MzRZUHU2aEU1ZmhudFMyOG90N1lZTzgKLS0tIHpmeHBzSGl2WjNBbDg0NkMrdXVJ
        YmQ0MElqSTlxazJJak5HUEZzZmJVSVkKaSeyRGA5ZALk82sW3sy7Wf9sYXPoRTsA
        jQkrv0w4hhM5Y0uI5j8o6rtfBu9UtAzCa2ugHRWPjLoCPHUX/A13uQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T19:56:28Z"
  mac: ENC[AES256_GCM,data:Xas8HhfMHaS2E+sU8ohMko3WwzlOMZsHZF/xuzfp5SQw9Rm/wB9PEt8UYUBSojvhi0npkizGqPd8gin7rXGNdceSHDh9R8RKPR3YVGzwqTbhaP160HK53E3n9Kkr/JfKxFfuYpeIozwXHsp2SaFbU7MnFSDCEtLXnPFeJvcx4Vc=,iv:SMb5YM6XZohaqi+wfRVp9+JXL3F7umJPkDGx0KEaur4=,tag:MZqZdeiJIDhSLwlABA+Gfw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
