# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:aSY5LKIm22BGfRZEK0WFs7UwMH5V+8F20GAVhjooH1hHfDJ3FV2fwQ==,iv:fbA97Na7FWGC9AQxQb4bCZ5cd1Lq/IxUNbd10gO74CM=,tag:G5z+dDMEQuKS6AWTeVs8iQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1agf0jp7qyqngf9kn5cn5cd9z24dgsu38rtu5l0hmjsfd6qn50pvsh38rsa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1THpEbzg1QXZRWmZPaDJy
        by9zVjJsZ3RPbHZ6SEV0QmdBanJ2U3R3OXgwCmxpRlRxN2VPdWwyd1QzUXFqVmRm
        Y09IeGV6dlVXR0JRT1I2RHY2V1hSS1kKLS0tIFJ0THNKMXNrUzkyY0grWUFtMXQy
        cXV6MWNRbzF2WlZhdkk2bXF0SHNDNEEKcWYk1kQaaatKGIlBo26qZgmIQAVsMgwp
        x5rf/qkDjpdiW1GznirFORpaMTksncMsfHP71rxzrP4+AgTMCxZPsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-19T16:02:18Z"
  mac: ENC[AES256_GCM,data:vMLHZoEZEfbZN3neb1QU/CjCvN664sTnfcy10yRh6mfaTM6dm/ebLG3grbw4okbXND9jwWSmcFx6FeIsZhF2zGQh1NsYDWni5eEoQ+sIOTQzIvJX3q8xOA7nt6QlE9PgOVgXpyJVRNK1diux+ahCAZV6PxGrrVsG1Es6XbCG774=,iv:ue16vHGmwYsQyiR1jF/PgVDNLqr5oQYfe7IkjvF0wEk=,tag:ZuvWJHBF/QnSVUMaW1hpQA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
