# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:FvxcFdOwGUgETg/hAeTterBPJVxDJwESkqWM+Ybmrv7yEKcB46uEEg==,iv:t4MNzfLQ92n5/XD/9hcLPVDVM6pgtR4rR8CZ8y6VFGw=,tag:jHgAi7NDvdtTJ/hhTFLPdA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTmRLcGhLNzJIdnlDN3V3
        UFp2SjdPNkI3bkthdWViOVRCWXlKMHdzR1ZNCk9sUTVOK3NZZUNqU1o0MEh5V3lQ
        cE9ubFJieU5tZUoyWEY2M0N4RTZhTVkKLS0tIDU2ckF6bitUTlhwTTVmV0NRYlpN
        YTRwMGZQYTk1QlAwdXZaS3lOS2FCYk0KqmAI2Oxks0sW8Do/sflb0PLbFYhZB67B
        /tj7LNM818o06HOAzcej0mtt2abaUXvOCVyC2LHXPsyCR0TIYtDUHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T19:38:27Z"
  mac: ENC[AES256_GCM,data:3x/InPZw7M6f5Gbd0flJNvkHocfNFL4G8uUU3Pi/jdcep7joYoJ1+1mhXCev2r++Hv9OrEoi/RewVyQrmXBaneZwliysQk+ydXlL2YyqzJWD0E+2lPF7AJfOVZL0gRhWaSjAYVRtRTIz5XAXp2OSlURxeS8WHQ5hlEcsLIdRD2k=,iv:ycivRPiqmuyXZYQS6DMhGXXgPdrd3pTgXU2VImtukWU=,tag:gyTFfRGNvHfqyQ8Q6mJEBg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
