---
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: vpn-egress
spec:
  selectors:
    - podSelector:
        matchLabels:
          vpn-routed: "true"
  destinationCIDRs:
    - 0.0.0.0/0
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/os: linux
    interface: "vlan2"